baseURL = "http://hack.negativetrust.zone"
languageCode = "en-us"
title = "NEGATIVE TRUST"
theme = "osprey"
canonifyURLS = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[Params]
    tagline = "this name doesn't make sense..."
    logoBig = ""
    logoSmall = ""
    favicon = "favicon.ico"
    opengraphImage = ""
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

